# Site settings
title: Apoorv Nandan's Notes
email: 
description: ""
baseurl: ""
url: "http://apoorvnandan.github.io"
twitter_username: NandanApoorv
github_username:  apoorvnandan

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
